modules/report/controllers/DefaultController.php
<?php
/*****************************************************************************************
 * EduSec  Open Source Edition is a School / College management system developed by
 * RUDRA SOFTECH. Copyright (C) 2010-2015 RUDRA SOFTECH.

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses. 

 * You can contact RUDRA SOFTECH, 1st floor Geeta Ceramics, 
 * Opp. Thakkarnagar BRTS station, Ahmedbad - 382350, India or
 * at email address info@rudrasoftech.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * RUDRA SOFTECH" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by RUDRA SOFTECH".
 *****************************************************************************************/
/**
 * Default controller use as a report dashboard
 *
 * @package EduSec.modules.report.controllers
 */

namespace app\modules\report\controllers;
use yii\web\JsExpression;
use yii\web\Controller;
use Yii;
use app\modules\student\models\StuMaster;
use app\modules\employee\models\EmpMaster;
use app\modules\course\models\Courses;
use app\modules\student\models\StuInfo;
use app\modules\student\models\StuCategory;
use yii\widgets\ActiveForm;
use yii\web\Response;
use yii\web\NotFoundHttpException;
use \app\modules\student\models\StuStatus;

class DefaultController extends Controller
{
    public function actionIndex()
    {
	$fYearWiseAdm = [];
	/**
	* @Start Display Category Wise Student Details Graph
	*/
	$stuCateDataTmp = StuCategory::find()->where(['is_status'=>0])->asArray()->all();	
	foreach($stuCateDataTmp as $cv) {
		$stuCatWiseDisp[] = $cv['stu_category_name'];
		$maleCount = (new \yii\db\Query())->from('stu_master sm')
		    ->join('JOIN', 'stu_info si', 'si.stu_info_stu_master_id = sm.stu_master_id')
		    ->where(['sm.is_status' => '0', 'si.stu_gender'=>'Male',  'sm.stu_master_category_id'=>$cv['stu_category_id']])->count();

		$femaleCount = (new \yii\db\Query())->from('stu_master sm')
		    ->join('JOIN', 'stu_info si', 'si.stu_info_stu_master_id = sm.stu_master_id')
		    ->where(['sm.is_status' => '0', 'si.stu_gender'=>'Female',  'sm.stu_master_category_id'=>$cv['stu_category_id']])->count();	
	
		$stuCatWiseDataMale[] = $maleCount;
		$stuCatWiseDataFemale[] = $femaleCount;
	}
	$stuCatWiseDisp[] = 'Not Set';
	$stuCatWiseDataMale[] = (new \yii\db\Query())->from('stu_master sm')
			->join('JOIN', 'stu_info si', 'si.stu_info_stu_master_id = sm.stu_master_id')
			->where(['sm.is_status'=>0, 'sm.stu_master_category_id'=>NULL, 'si.stu_gender'=>'Male'])->count();
	$stuCatWiseDataFemale[] = (new \yii\db\Query())->from('stu_master sm')
			->join('JOIN', 'stu_info si', 'si.stu_info_stu_master_id = sm.stu_master_id')
			->where(['sm.is_status'=>0, 'sm.stu_master_category_id'=>NULL, 'si.stu_gender'=>'Female'])->count();
	

    /**
	 * @Start Display Student Status Wise Details in combine graph
	 */
	$dataRegTmp = $courseData = [];
	$stuRegStat = StuMaster::find()->where(['is_status'=>0, 'stu_master_stu_status_id'=>0])->count();
	$stuStatusWise[] = ['name'=>"Default ($stuRegStat)", 'y'=>$stuRegStat, 'color'=>'#77C730'];

	$courseDataTmp = Courses::find()->where(['is_status'=>0])->asArray()->limit(10)->orderBy('course_id DESC')->all();
	$stuStatusDataTmp = StuStatus::find()->where(['is_status'=>0])->orderBy('stu_status_id')->asArray()->all();

	foreach($courseDataTmp as $v) {
		$stuCourseRegStat = StuMaster::find()->where(['is_status'=>0, 'stu_master_stu_status_id'=>0, 'stu_master_course_id'=>$v['course_id']])->count();
		$dataRegTmp[] = $stuCourseRegStat;
		$courseData[] = $v['course_name'];
	}
	$stuStatusData[] = ['name'=>"Default ($stuRegStat)", 
			  'type'=>'column',
			  'data'=>$dataRegTmp,
			  'color'=>'#77C730',
			];
	//print_r($stuStatusData); exit;

	foreach($stuStatusDataTmp as $k=>$sv) 
	{
		$dataTmp = [];
		foreach($courseDataTmp as $v) {
			$stuCourseStat = StuMaster::find()->where(['is_status'=>0, 'stu_master_course_id'=>$v['course_id'], 'stu_master_stu_status_id'=>$sv['stu_status_id']])->count();
			
			$dataTmp[] = $stuCourseStat;
		}

		$stuStatusWiseCount = StuMaster::find()->where(['is_status'=>0, 'stu_master_stu_status_id'=>$sv['stu_status_id']])->count();
		$stuStatusData[] = ['name'=>$sv['stu_status_name']."($stuStatusWiseCount)", 
				       'type'=>'column',
				       'data'=>$dataTmp,
					
				 ];
		$stuStatusWise[] = ['name'=>$sv['stu_status_name'].' ('.$stuStatusWiseCount.')',
				    'y'=>$stuStatusWiseCount,
				    'color'=>new JsExpression('Highcharts.getOptions().colors['.($k).']')
				];
		
	}

	/**
	* @Start Gender Wise Data Display For Student
	*/
	$stuGenWise = (new \yii\db\Query())
		    ->select(["CONCAT(IFNULL(si.stu_gender, 'Not Set'), ' (', COUNT( stu_master_id ), ')') AS '0'", 'COUNT(stu_master_id) AS "1"']) 
		    ->from('stu_master sm')
		    ->join('JOIN', 'stu_info si', 'si.stu_info_stu_master_id = sm.stu_master_id')
		    ->where(['sm.is_status' => '0'])
		    ->groupBy('si.stu_gender')
		    ->orderBy('si.stu_gender ASC')
		    ->all();
	if($stuGenWise)
	    $stuGenWise[0][0] = "Not Set".$stuGenWise[0][0];


	/**
	* @Start Gender Wise Data Display For Employee
	*/
	$empGenWise = (new \yii\db\Query())
		    ->select(["CONCAT(IFNULL(ei.emp_gender, 'Not Set'), ' (', COUNT( emp_master_id ), ')') AS '0'", 'COUNT(emp_master_id) AS "1"']) 
		    ->from('emp_master em')
		    ->join('JOIN', 'emp_info ei', 'ei.emp_info_emp_master_id = em.emp_master_id')
		    ->where(['em.is_status' => '0'])
		    ->groupBy('ei.emp_gender')
		    ->orderBy('ei.emp_gender ASC')
		    ->all();
	if($empGenWise)
	$empGenWise[0][0] = "Not Set".$empGenWise[0][0];


	/**
	* @Start Year wise employee joining
	*/
	$empYearWiseJoin = $depDisp = [];
	$empYearJoin = (new \yii\db\Query())
		    ->select(["CONCAT(DATE_FORMAT(ei.emp_joining_date, '%Y'), ' (', COUNT(em.emp_master_id), ')') AS 'yearDisp'", 'DATE_FORMAT(ei.emp_joining_date, "%Y") as "year"']) 
		    ->from('emp_master em')
		    ->join('JOIN', 'emp_info ei', 'ei.emp_info_emp_master_id = em.emp_master_id')
		    ->where(['em.is_status' => '0'])
		    ->groupBy(['DATE_FORMAT(ei.emp_joining_date, "%Y")'])
		    ->orderBy('YEAR(ei.emp_joining_date) DESC')
		    ->limit('3')
		    ->all();

	foreach($empYearJoin as $k=>$v) {
		$yearResults = $deptCount =  $depDisp = [];
		$deptData = \app\modules\employee\models\EmpDepartment::find()->where(['is_status'=>0])->limit(10)->orderBy('emp_department_id DESC')->asArray()->all();
		foreach($deptData as $k=>$dv) {
		    $deptCountTmp = (new \yii\db\Query())->from('emp_master em')
			->join('JOIN', 'emp_info ei', 'ei.emp_info_emp_master_id = em.emp_master_id')
			->where(['YEAR(ei.emp_joining_date)' => $v['year'], 'emp_master_department_id' => $dv['emp_department_id'], 'is_status'=>0])->count();
		    $deptCount[] = $deptCountTmp;
		    $depDisp[] = $dv['emp_department_alias'];
		}
		$yearResults = ['name'=>!empty($v['yearDisp']) ? $v['yearDisp'] : "Not Set", 'data'=>$deptCount];
		$empYearWiseJoin[] = $yearResults;	
	}
        return $this->render('index', ['stuCatWiseDataMale'=>$stuCatWiseDataMale,
				       'stuCatWiseDataFemale'=>$stuCatWiseDataFemale,
				       'stuCatWiseDisp'=>$stuCatWiseDisp,
				       'stuStatusWise'=>$stuStatusWise,
				       'stuGenWise'=>$stuGenWise,
				       'empYearWiseJoin'=>$empYearWiseJoin,
				       'depDisp'=>$depDisp,
				       'courseData'=>$courseData,
				       'stuStatusData'=>$stuStatusData,
				       'empGenWise'=>$empGenWise,
				]
			);
    }
    

   
}

modules/report/controllers/EmployeeController.php
<?php
/*****************************************************************************************
 * EduSec  Open Source Edition is a School / College management system developed by
 * RUDRA SOFTECH. Copyright (C) 2010-2015 RUDRA SOFTECH.

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses. 

 * You can contact RUDRA SOFTECH, 1st floor Geeta Ceramics, 
 * Opp. Thakkarnagar BRTS station, Ahmedbad - 382350, India or
 * at email address info@rudrasoftech.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * RUDRA SOFTECH" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by RUDRA SOFTECH".
 *****************************************************************************************/
/**
 * Employee controller its content employee related details
 *
 * @package EduSec.modules.report.controllers
 */

namespace app\modules\report\controllers;

use yii\web\Controller;
use Yii;
use app\modules\employee\models\EmpMasterSearch;
use app\modules\student\models\StuMasterSearch;
use app\modules\student\models\StuMaster;
use app\modules\student\models\StuInfo;
use app\models\City;
use yii\widgets\ActiveForm;
use yii\web\Response;
use yii\web\NotFoundHttpException;

class EmployeeController extends Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

    /* Employee Info Dynamic Report */
    public function actionEmpinforeport()
    {
	$selected_list = $query = NULL;
	$employee_data= array();
		
	 if((!empty($_POST['department'])||!empty($_POST['designation'])||!empty($_POST['gender'])||!empty($_POST['city'])||!empty($_POST['category'])) && !empty($_POST['e_info']))
	{
		if(!empty($_POST['department']))
		{
			$query .="emp.emp_master_department_id=".$_POST['department']. " AND ";
		}
		if(!empty($_POST['designation']))
		{
			$query .="emp.emp_master_designation_id=".$_POST['designation']. " AND ";
		}
		if(!empty($_POST['city']))
		{
			$query .="emp.emp_master_emp_address_id=".$_POST['city']. " AND ";
		}
		if(!empty($_POST['category']))
		{
			$query .="emp.emp_master_category_id=".$_POST['category']. " AND ";	
		}
		if(!empty($_POST['gender']))
		{
			$query .="e_info.emp_gender='".$_POST['gender']. "'"." AND ";
		}
		if(!empty($_POST['e_info']))
		{
			$selected_list = $_POST['e_info'];
		}
		
		$selected_list = $_POST['e_info'];		

		$employee_d = new \yii\db\Query();
		$employee_d ->select('*')
			->from('emp_master emp')
			->join('join','emp_info e_info', 'e_info.emp_info_id = emp.emp_master_emp_info_id')
			->join('join','emp_department emp_dep','emp_dep.emp_department_id = emp.emp_master_department_id ')
			->join('join','emp_designation emp_des','emp_des.emp_designation_id = emp.emp_master_designation_id ')
			->join('join','emp_category emp_cat','emp_cat.emp_category_id = emp. 	emp_master_category_id')
			->leftJoin('emp_address eadd', 'eadd.emp_address_id = emp.emp_master_emp_address_id')
			->where($query.'emp.is_status = 0');
	
			  $command = $employee_d->createCommand();
			  $employee_data = $command->queryAll();

		if(empty($employee_data))
		{		
		 \Yii::$app->getSession()->setFlash('emperror',"<i class='fa fa-exclamation-triangle'></i> <b> No Record Found For This Criteria.</b>");		
			return $this->redirect(['empinforeport']);			
		}					
		return $this->render('emp_info_report',[
      			'employee_data'=>$employee_data,'selected_list'=>$selected_list,'query'=>$query,
			]);	
		break;		
	}
	return $this->render('emp_report_view',['selected_list'=>$selected_list, 'query' => $query,]);
	
    }     
	// employee  info report export to pdf and excel file action
	public function actionSelectedEmployeeList()
	{		
		if(!empty($_REQUEST['employeelistexport']))
		{
			$query=null;
			$query= $_SESSION['query'];
			$selected_list=$_SESSION['selected_list'];
			$query1= new \yii\db\Query();
		 $query1-> select('*')
		        ->from('emp_master emp')
			->join('join','emp_info e_info', 'e_info.emp_info_id = emp.emp_master_emp_info_id')
			->join('join','emp_department emp_dep','emp_dep.emp_department_id = emp.emp_master_department_id ')
			->join('join','emp_designation emp_des','emp_des.emp_designation_id = emp.emp_master_designation_id ')
			->join('join','emp_category emp_cat','emp_cat.emp_category_id = emp. 	emp_master_category_id')
			->leftJoin('emp_address eadd', 'eadd.emp_address_id = emp.emp_master_emp_address_id')
			->where($query.'emp.is_status = 0');
			$command=$query1->createCommand();
			$employee_data=$command->queryAll();
			
			$html = $this->renderPartial('emp_info_report_pdf', array(
				'employee_data'=>$employee_data, 
				'selected_list'=>$selected_list,
			));
		
			ob_clean();
			return Yii::$app->pdf->exportData('Employee Info Report','Employee_info_report',$html);		
		}
		else if(!empty($_REQUEST['employeelistexcelexport']))
		{
			$query=null;
			$query= $_SESSION['query'];
			$selected_list=$_SESSION['selected_list'];
			
			$query1= new \yii\db\Query();
			$query1 -> select('*')
			       ->from('emp_master emp')
				->join('join','emp_info e_info', 'e_info.emp_info_id = emp.emp_master_emp_info_id')
				->join('join','emp_department emp_dep','emp_dep.emp_department_id = emp.emp_master_department_id ')
				->join('join','emp_designation emp_des','emp_des.emp_designation_id = emp.emp_master_designation_id ')
				->join('join','emp_category emp_cat','emp_cat.emp_category_id = emp. 	emp_master_category_id')
				->leftJoin('emp_address eadd', 'eadd.emp_address_id = emp.emp_master_emp_address_id')
				->where($query.'emp.is_status = 0');

			$command=$query1->createCommand();
			$employee_data=$command->queryAll();
			
				$file = $this->renderPartial('emp_info_report_excel', array(
					'employee_data'=>$employee_data, 
					'selected_list'=>$selected_list,
				    ));
			$fileName = "Employee_info_report".date('YmdHis').'.xls';	
			$options = ['mimeType'=>'application/vnd.ms-excel'];

			return Yii::$app->excel->exportExcel($file, $fileName, $options);
		}		
		else
		{		
			$query=$_SESSION['query'];
			$selected_list=null;
		}
	}
}

modules/report/views/employee/emp_info_report.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\grid\GridView;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use app\models\City;
use app\models\State;
use app\models\Country;
use yii\web\Controller;
use app\modules\employee\models\EmpInfo;
use app\modules\employee\models\EmpAddress;
use app\modules\employee\models\EmpMaster;
use app\modules\employee\models\EmpDepartment;
use app\modules\employee\models\EmpDesignation;

$this->title = Yii::t('app', 'Employee Info Report');
$this->params['breadcrumbs'][] = $this->title;

$_SESSION['query']=$query;
$_SESSION['selected_list']=$selected_list;
?>

<div class="row">
  <div class="col-xs-12">
     <div class="box box-primary">

       <div class="box-header">
	          <h3 class="box-title"><i class="fa fa-info-circle"></i> <?= $this->title ?></h3>
          <div class="box-tools pull-right">
          	<?php echo Html::a('<i class="fa fa-arrow-circle-left"></i> Back', ['employee/empinforeport'], ['class'=>'btn btn-back', 'style'=>'color:#fff']);?> &nbsp;
<?php echo Html::a('<i class="fa fa-file-excel-o"></i> Excel',['employee/selected-employee-list','employeelistexcelexport'=>'employeelistexcel'],array('title'=>'Export to Excel', 'target'=>'_blank', 'class'=>'btn btn-info', 'style'=>'color:#fff'));?> &nbsp;
<?php echo Html::a('<i class="fa fa-file-pdf-o"></i> PDF',array('employee/selected-employee-list','employeelistexport'=>'employeelistpdf'),array('title'=>'Export to PDF','target'=>'_blank','class'=>'btn btn-warning', 'style'=>'color:#fff')); ?>	
          </div> <!-- box-tools -->
        </div><!-- /.box-header -->

 <div class="box-body table-responsive no-padding">
 <?php $add_c = $add_city = $add_co = $add_s = null;
if(!empty($employee_data) && !empty($selected_list))
{
	$emp_info = new EmpInfo();
	echo "<table class ='table-bordered table table-striped'>";	
	echo "<tr><th class='text-center'>SI No.</th>";
	foreach($selected_list as $s)
	{
		if($s == 'emp_department_name')
			echo "<th class='text-center'>Department</th>";
		else if($s == 'emp_cadd')
			echo "<th class='text-center'>Local Address</th>";
		else if($s == 'emp_padd')
			echo "<th class='text-center'>International Address</th>";
		else if($s == 'emp_category_name')
			echo "<th class='text-center'>Category</th>";
		else if($s == 'emp_designation_name')
			echo "<th class='text-center'>Designation</th>";
		else if($s == 'city')
			echo "<th class='text-center'>City</th>";
		else if($s == 'emp_bloodgroup')
			echo "<th class='text-center'>Blood Group</th>";
		else if($s == 'emp_joining_date')
			echo "<th class='text-center'>Joining Date </th>";
		else if($s == 'emp_guardian_mobile_no')
			echo "<th class='text-center'>Guardian No</th>";
		else if($s == 'emp_email_id')
			echo "<th class='text-center'>".Html::activeLabel($emp_info,$s)."</th>";
		else
			echo "<th class='text-center'>".Html::activeLabel($emp_info,$s)." </th>";
	}
	echo "</tr>";
	$i = 1;
	$m = 1;	
	foreach($employee_data as $t=>$sd)
	{ 		
		echo "<tr>";
		echo "<td class='text-center'>".$i."</td>";
		foreach($selected_list as $s)
		{
			if($s == 'emp_department_name')
				echo "<td class='text-center'>".EmpDepartment::findOne($sd['emp_master_department_id'])->emp_department_name."</td>";
			else if($s == 'city')
			{
				if($sd['emp_master_emp_address_id'] !=0)
				{
					$add = EmpAddress::findOne($sd['emp_master_emp_address_id']);
					if($add->emp_cadd_city != null)
					echo "<td class='text-center'>".City::findOne($add->emp_cadd_city)->city_name."</td>";			
					else
					echo "<td>&nbsp;</td>";
				}
				else
				echo "<td>&nbsp;</td>";
			}
			else if($s == 'emp_designation_name'){
				if($sd['emp_master_designation_id']!= null)
					echo "<td class='text-center'>".EmpDesignation::findOne($sd['emp_master_designation_id'])->emp_designation_name."</td>";
				else
					echo "<td> &nbsp;</td>";
			}
			else if($s == 'emp_category_name'){
				echo "<td class='text-center'>".EmpCategory::findOne($sd['emp_master_category_id'])->emp_category_name."</td>";	
			}			
		        else if($s == 'emp_cadd')
			{	
				if($sd['emp_master_emp_address_id']!=0)
				{
					if(!empty(EmpAddress::findOne($sd['emp_master_emp_address_id'])->emp_cadd_city))
					{
						$add_c = "<br/>".City::findOne(EmpAddress::findOne($sd['emp_master_emp_address_id'])->emp_cadd_city)->city_name.", ";	
					}
					else
					{
						$add_c = '';
					}					
					if(!empty(EmpAddress::findOne($sd['emp_master_emp_address_id'])->emp_cadd_state))
					{
						$add_s = State::findOne(EmpAddress::findOne($sd['emp_master_emp_address_id'])->emp_cadd_state)->state_name.", ";	
					}
					else
					{
						$add_s = '';
					}
					if(!empty(EmpAddress::findOne($sd['emp_master_emp_address_id'])->emp_cadd_country))
					{
						$add_co = Country::findOne(EmpAddress::findOne($sd['emp_master_emp_address_id'])->emp_cadd_country)->country_name;	
					}
					else
					{
						$add_co = '';
					}					
					echo "<td class='text-center'>".EmpAddress::findOne($sd['emp_master_emp_address_id'])->emp_cadd." ".$add_c." ".$add_s." ".$add_co."</td>";
					
				}
				else
					echo "<td class='text-center'>&nbsp;</td>";
			}
			else if($s == 'emp_padd')
			{	
				if($sd['emp_master_emp_address_id']!=0)
				{
					if(!empty(EmpAddress::findOne($sd['emp_master_emp_address_id'])->emp_padd_city))
					{
						$add_c = "<br/>".City::findOne(EmpAddress::findOne($sd['emp_master_emp_address_id'])->emp_padd_city)->city_name.", ";	
					}
					else
					{
						$add_c = '';
					}					
					if(!empty(EmpAddress::findOne($sd['emp_master_emp_address_id'])->emp_padd_state))
					{
						$add_s = State::findOne(EmpAddress::findOne($sd['emp_master_emp_address_id'])->emp_padd_state)->state_name.", ";	
					}
					else
					{
						$add_s = '';
					}
					if(!empty(EmpAddress::findOne($sd['emp_master_emp_address_id'])->emp_padd_country))
					{
						$add_co = Country::findOne(EmpAddress::findOne($sd['emp_master_emp_address_id'])->emp_padd_country)->country_name;	
					}
					else
					{
						$add_co = '';
					}
				echo "<td class='text-center'>".EmpAddress::findOne($sd['emp_master_emp_address_id'])->emp_padd." ".$add_c." ".$add_s." ".$add_co."</td>";
				}
				else  {
				echo "<td>&nbsp;</td>";
				  }				
			}				
			else if($s == 'emp_joining_date')
			{
				$jdate = EmpInfo::findOne($sd['emp_master_emp_info_id'])->$s;
				echo "<td class='text-center'>".date('d-m-Y',strtotime($jdate))."</td>";	
			}
			else if($s == 'emp_dob')
			{
				$bdate = EmpInfo::findOne($sd['emp_master_emp_info_id'])->$s;
				echo "<td class='text-center'>".date('d-m-Y',strtotime($bdate))."</td>";	
			}
			else
			{
				echo "<td class='text-center'>".EmpInfo::findOne($sd['emp_master_emp_info_id'])->$s."</td>";
			}
		}
		$i++;
		echo "</tr>";
		$m++;		
	}
 echo"</table>";
}
?>
</div></div>
</div> <!---/end box-body--->
</div> <!---/end box--->