modules/fees/controllers/DependentController.php
<?php
/*****************************************************************************************
 * EduSec  Open Source Edition is a School / College management system developed by
 * RUDRA SOFTECH. Copyright (C) 2010-2015 RUDRA SOFTECH.

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses. 

 * You can contact RUDRA SOFTECH, 1st floor Geeta Ceramics, 
 * Opp. Thakkarnagar BRTS station, Ahmedbad - 382350, India or
 * at email address info@rudrasoftech.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * RUDRA SOFTECH" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by RUDRA SOFTECH".
 *****************************************************************************************/
/**
 * Dependent controller it use ajax request.
 *
 * @package EduSec.modules.fees.controllers
 */

namespace app\modules\fees\controllers;
use yii\helpers\Html;
use yii\web\Controller;

class DependentController extends Controller
{

	//Get fees category based on batch selection in fees collection
	public function actionGetFeesCategory($id) 
	{
		$rows = \app\modules\fees\models\FeesCollectCategory::find()->where(['is_status'=>0, 'fees_collect_batch_id'=>$id])->all();	
		echo Html::tag('option', Html::encode('---Select Fees Collect Category---'), ['value'=>'']); 
		foreach($rows as $row)
			echo Html::tag('option',Html::encode($row->fees_collect_name), ['value'=>$row->fees_collect_category_id]); 
    	}

}

modules/fees/controllers/FeesPaymentTransactionController.php
<?php
/*****************************************************************************************
 * EduSec  Open Source Edition is a School / College management system developed by
 * RUDRA SOFTECH. Copyright (C) 2010-2015 RUDRA SOFTECH.

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses. 

 * You can contact RUDRA SOFTECH, 1st floor Geeta Ceramics, 
 * Opp. Thakkarnagar BRTS station, Ahmedbad - 382350, India or
 * at email address info@rudrasoftech.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * RUDRA SOFTECH" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by RUDRA SOFTECH".
 *****************************************************************************************/
/**
 * FeesPaymentTransactionController implements the CRUD actions for FeesPaymentTransaction model.
 *
 * @package EduSec.modules.fees.controllers
 */

namespace app\modules\fees\controllers;
use Yii;
use app\modules\fees\models\FeesPaymentTransaction;
use app\modules\fees\models\FeesPaymentTransactionSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Json;
use yii\widgets\ActiveForm;
use mPDF;

class FeesPaymentTransactionController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
		    'export-fcc-wise-fees-pdf' => ['post'],
                ],
            ],
        ];
    }

    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Display student list based on fees category batch.
     * @return mixed
     */
    public function actionCollect()
    {
        $FptModel = new FeesPaymentTransaction();
		$FccModel = new \app\modules\fees\models\FeesCollectCategory();
		$dispStatus = false;
        if(!empty($_POST['FeesCollectCategory']['fees_collect_category_id'])) {
			$dispStatus = true;
			$FccModel = \app\modules\fees\models\FeesCollectCategory::findOne($_POST['FeesCollectCategory']['fees_collect_category_id']);
        }

	return $this->render('collect', [
		'FptModel' => $FptModel,
		'FccModel' => $FccModel,
		'dispStatus'=> $dispStatus,
	]);
        
    }

    /**
     * Generate PDF file based on fees collection category wise.
     * @return Export PDF Data
     */
    public function actionExportFccWiseFeesPdf($fccid)
    {
	$FptModel = new FeesPaymentTransaction();
	$FccModel = \app\modules\fees\models\FeesCollectCategory::findOne($fccid);
	$html = $this->renderPartial('ExportFccWiseFeesPdf', [
		'FptModel' => $FptModel,
		'FccModel' => $FccModel,
	]);
	$fileName = $FccModel->fees_collect_name."_".date('Ymd-His');
	return Yii::$app->pdf->exportData($FccModel->fees_collect_name.' Report', $fileName,$html);
    }

    /**
     * Take Fees based on fees category wise & student wise.
     * @param integer $sid, $fcid
     * @return mixed
     */
    public function actionPayFees($sid, $fcid)
    {
        $model = new FeesPaymentTransaction();
	$stuData = \app\modules\student\models\StuMaster::findOne($sid);
	$FccModel = \app\modules\fees\models\FeesCollectCategory::findOne($fcid);
        if($model->load(Yii::$app->request->post())) {

   	    $model->created_at = new \yii\db\Expression('NOW()');
	    $model->created_by = Yii::$app->getid->getId();
	    $model->fees_pay_tran_collect_id = $fcid;
	    $model->fees_pay_tran_stu_id = $stuData->stu_master_id;
	    $model->fees_pay_tran_batch_id = $stuData->stu_master_batch_id;
	    $model->fees_pay_tran_course_id = $stuData->stu_master_course_id;
	    $model->fees_pay_tran_section_id = $stuData->stu_master_section_id;
	
	    if(!empty($model->fees_pay_tran_date)) {
		$model->fees_pay_tran_date = Yii::$app->dateformatter->getDateFormat($model->fees_pay_tran_date);
	    }
	    if(!empty($model->fees_pay_tran_cheque_date)) {
	   	 $model->fees_pay_tran_cheque_date = Yii::$app->dateformatter->getDateFormat($model->fees_pay_tran_cheque_date);
	    }
	    if($model->save() && $model->validate()) 
            	return $this->redirect(['pay-fees', 'sid' => $sid, 'fcid'=>$fcid]);

        } 
	return $this->render('create', [
		'model' => $model,
		'stuData' => $stuData,
		'FccModel'=> $FccModel,
	]);
        
    }

    /**
     * Update Fees taken details for individual receipt wise.
     * @param integer $id
     * @return mixed
     */ 
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
	$stuData = \app\modules\student\models\StuMaster::findOne($model->fees_pay_tran_stu_id);
	$FccModel = \app\modules\fees\models\FeesCollectCategory::findOne($model->fees_pay_tran_collect_id);
        if($model->load(Yii::$app->request->post())) {
   	    $model->updated_at = new \yii\db\Expression('NOW()');
	    $model->updated_by = Yii::$app->getid->getId();

	     if(!empty($model->fees_pay_tran_date)) {
		$model->fees_pay_tran_date = Yii::$app->dateformatter->getDateFormat($model->fees_pay_tran_date);
	    }
	    if(!empty($model->fees_pay_tran_cheque_date)) {
	   	 $model->fees_pay_tran_cheque_date = Yii::$app->dateformatter->getDateFormat($model->fees_pay_tran_cheque_date);
	    }
	    if($model->save()) 
            	return $this->redirect(['pay-fees', 'sid' => $model->fees_pay_tran_stu_id, 'fcid'=>$model->fees_pay_tran_collect_id]);

        } 
            return $this->render('update', [
                'model' => $model,
		'stuData' => $stuData,
		'FccModel'=> $FccModel,
            ]);
    }

   /**
     * Display Fees category wise & student wise fees receipt.
     * @param integer $sid, $fcid
     * @return mixed
     */ 
    public function actionPrintCommonReceipt($sid, $fcid)
    {
		$model = new FeesPaymentTransaction();
		$stuData = \app\modules\student\models\StuMaster::findOne($sid);
		$FccModel = \app\modules\fees\models\FeesCollectCategory::findOne($fcid);
		$title = "Receipt of ".$stuData->stuMasterStuInfo->name.' : '.Yii::$app->dateformatter->getDateDisplay(date('Y-m-d'));
		$html = $this->renderPartial('print-common-receipt', [
					'model' => $model,
					'stuData' => $stuData,
					'FccModel'=> $FccModel,
					'title'=>$title,
				]);
				
		$imgSrc = Yii::$app->urlManager->createAbsoluteUrl('site/loadimage');
		$mpdf = new mPDF('utf-8', 'A4',0,'',15,15,25,16,4,9,'P');
		$mpdf->WriteHTML('<watermarkimage src='.$imgSrc.' alpha="0.33" size="50,30"/>');
		$mpdf->showWatermarkImage = true;
		$mpdf->WriteHTML($html);
		$mpdf->Output($title.'.pdf', "I");
    }

   /**
     * Display Individual Student Fees Data.
     * If student is login, the fees data display based on student login id other wise request id.
     * @param integer $sid
     * @return mixed
     */     
    public function actionStuFeesData()
    {
	if(Yii::$app->session->get('stu_id'))
		$sid = Yii::$app->session->get('stu_id');
	else if(!empty($_REQUEST['sid'])) 
		$sid = $_REQUEST['sid'];
	else 
		throw new \yii\web\BadRequestHttpException("Missing required parameters: sid");

	$model = new FeesPaymentTransaction();
	$stuData = \app\modules\student\models\StuMaster::findOne($sid);
	$FccModel = new \app\modules\fees\models\FeesCollectCategory();

	return $this->render('stu-fees-data', [
                'model' => $model,
		'stuData' => $stuData,
		'FccModel'=> $FccModel,
            ]);
    } 
    
   /**
     * Deletes an existing FeesPaymentTransaction model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */ 
    public function actionDelete($id)
    {
	$model = $this->findModel($id);
	$model->is_status = 2;
	$model->updated_at = new \yii\db\Expression('NOW()');
	$model->updated_by = Yii::$app->getid->getId();
	$model->update(false, ['is_status', 'updated_at', 'updated_by']);

	if(Yii::$app->request->referrer) {
	    return $this->redirect(Yii::$app->request->referrer);
	}else{
	    return $this->goHome();
	}
    }

    /**
     * Finds the FeesPaymentTransaction model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return FeesPaymentTransaction the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */   
    protected function findModel($id)
    {
        if (($model = FeesPaymentTransaction::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

modules/fees/views/fees-payment-transaction/ExportFccWiseFeesPdf.php
<?php 
use yii\helpers\Html;
?>
<html>
<head>
	<title>Fees Collection Category Wise PDF Report</title>
</head>
<body>
<?php
	$totalAmount = $gTotalAmount = $gpayFees = $gActualCollect = $payFees = $actualCollect = 0;
	$stuDataTmp = Yii::$app->db->createCommand("SELECT stu_master_id FROM stu_master WHERE stu_master_batch_id=".$FccModel->fees_collect_batch_id." AND is_status=0")->queryColumn();
	$payFeesTmp = Yii::$app->db->createCommand("SELECT fees_pay_tran_stu_id FROM fees_payment_transaction WHERE fees_pay_tran_batch_id=".$FccModel->fees_collect_batch_id." AND is_status=0 AND fees_pay_tran_collect_id=".$FccModel->fees_collect_category_id)->queryColumn();
	$stuData = array_unique(array_merge($stuDataTmp, $payFeesTmp));
	$feesData = \app\modules\fees\models\FeesPaymentTransaction::find()->where(['fees_pay_tran_batch_id' => $FccModel->fees_collect_batch_id, 'is_status'=>0])->asArray()->all();
	$totalAmountTmp = \app\modules\fees\models\FeesCategoryDetails::getFeeCategoryTotal($FccModel->fees_collect_category_id);
	$totalAmount = (!$totalAmountTmp) ? 0 : $totalAmountTmp; 
	
?>
<div class="grid-view">
<?php
	if(!empty($stuData)) {
		echo '<table class="table table-striped">';
		echo '<tr>';
		echo '<th class="text-center">SI No.</th>';
		echo '<th>Student No</th>';
		echo '<th>Student Name</th>';
		echo '<th>Total Collection</th>';
		echo '<th>Paid Amount</th>';
		echo '<th>Unpaid Amount</th>';
		echo '</tr>';
		$sr = 1;
		foreach($stuData as $key=>$value) {
			$stuDetails = \app\modules\student\models\StuMaster::findOne($value);
			echo '<tr>';		
			echo '<td class="text-center">'.$sr++.'</td>';
			echo '<td>'.(!empty($stuDetails->stuMasterStuInfo->stu_unique_id) ? $stuDetails->stuMasterStuInfo->stu_unique_id : "(Not Set)").'</td>';
			echo '<td>'.$stuDetails->stuMasterStuInfo->name.'</td>';
			echo '<td>'.$totalAmount.'</td>';
			$payFees = $FptModel->getStuTotalPayFees($value, $FccModel->fees_collect_category_id);
			echo '<td>'.(!empty($payFees) ? $payFees : "0").'</td>';
			echo '<td>'.$actualCollect = ($totalAmount-$payFees).'</td>';
			echo '</tr>';
			$gTotalAmount+=$totalAmount;
			$gpayFees+=$payFees;
			$gActualCollect+=$actualCollect;
		}
		echo '<tr class="bg-aqua"><th colspan="3" class="text-right">GRAND TOTAL </th>';
		echo '<th>'.$gTotalAmount.'</th>';
		echo '<th>'.$gpayFees.'</th>';
		echo '<th>'.$gActualCollect.'</th>';
		echo '</tr>';
		echo '</table>';	
	}
	else {
		echo '<div class="alert alert alert-danger">No student data available</div>';
	}
   ?>
</div>
</body>
</html>

modules/fees/views/fees-payment-transaction/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\fees\models\FeesPaymentTransactionSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="fees-payment-transaction-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'fees_pay_tran_id') ?>

    <?= $form->field($model, 'fees_pay_tran_collect_id') ?>

    <?= $form->field($model, 'fees_pay_tran_stu_id') ?>

    <?= $form->field($model, 'fees_pay_tran_batch_id') ?>

    <?= $form->field($model, 'fees_pay_tran_course_id') ?>

    <?php // echo $form->field($model, 'fees_pay_tran_section_id') ?>

    <?php // echo $form->field($model, 'fees_pay_tran_mode') ?>

    <?php // echo $form->field($model, 'fees_pay_tran_cheque_no') ?>

    <?php // echo $form->field($model, 'fees_pay_tran_bank_id') ?>

    <?php // echo $form->field($model, 'fees_pay_tran_amount') ?>

    <?php // echo $form->field($model, 'fees_pay_tran_date') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <?php // echo $form->field($model, 'is_status') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/fees/views/fees-payment-transaction/collect.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\bootstrap\Modal;

$this->title = "Fees Collection";
$this->params['breadcrumbs'][] = ['label' => 'Fees', 'url'=>['/fees']];
$this->params['breadcrumbs'][] = ['label' => $this->title, 'url'=>['collect']];

?>

<!---Start Select Fees Collection Category---> 
<div class="box-info box box-solid view-item col-xs-12 col-lg-12 no-padding">
    <div class="box-header with-border">
	<h3 class="box-title"><i class="fa fa-search"></i> Select Criteria</h3>
    </div>
    <div class="box-body no-padding">
	<?php $form = ActiveForm::begin([
		'id' => 'fees-collect-form',
		'fieldConfig' => [
			'template' => "{label}{input}{error}",
		],
	]); ?>

    	<div class="col-md-6">
		<?= $form->field($FccModel, 'fees_collect_batch_id')->dropDownList(ArrayHelper::map(app\modules\course\models\Batches::find()->where(['is_status'=>0])->all(), 'batch_id','batch_name', 'batchCourse.course_name'), 
		[
			'prompt'=>'Select Batch',
			'onchange'=>'
				$.get("'.Url::toRoute('dependent/get-fees-category').'", { id: $(this).val() } )
				.done(function( data ) {
				$( "#'.Html::getInputId($FccModel, 'fees_collect_category_id').'" ).html( data );
				}
			);'    
		]); 
		$fccData = [];
		if(!empty($FccModel->fees_collect_batch_id)) {
			$fccData = ArrayHelper::map(app\modules\fees\models\FeesCollectCategory::find()->where(['is_status'=>0, 'fees_collect_batch_id'=>$FccModel->fees_collect_batch_id])->all(), 'fees_collect_category_id', 'fees_collect_name');	
		}
	?>
	</div>

	<div class="col-md-6">
	<?= $form->field($FccModel, 'fees_collect_category_id')->dropDownList($fccData,
	[
		'prompt'=>'Select Fees Category',
		'onchange'=>'this.form.submit()',
	]); ?>
	</div>

	<?php ActiveForm::end(); ?>
    </div>
</div>
<!---End Select Fees Collection Category---> 

<?php 
if($dispStatus) :
	$totalAmount = $gTotalAmount = $gpayFees = $gActualCollect = $payFees = $actualCollect = 0;
	$feesDetails = \app\modules\fees\models\FeesCategoryDetails::find()->where(['fees_details_category_id' => $FccModel->fees_collect_category_id, 'is_status'=>0])->asArray()->all();
	$stuDataTmp = Yii::$app->db->createCommand("SELECT stu_master_id FROM stu_master WHERE stu_master_batch_id=".$FccModel->fees_collect_batch_id." AND is_status=0")->queryColumn();
	$payFeesTmp = Yii::$app->db->createCommand("SELECT fees_pay_tran_stu_id FROM fees_payment_transaction WHERE fees_pay_tran_batch_id=".$FccModel->fees_collect_batch_id." AND is_status=0 AND fees_pay_tran_collect_id=".$FccModel->fees_collect_category_id)->queryColumn();
	$stuData = array_unique(array_merge($stuDataTmp, $payFeesTmp));

	$feesData = \app\modules\fees\models\FeesPaymentTransaction::find()->where(['fees_pay_tran_batch_id' => $FccModel->fees_collect_batch_id, 'is_status'=>0])->asArray()->all();
	
?>

<!---Start display fees collection details---> 
<div class="box-primary box view-item col-xs-12 col-lg-12 no-padding">
   <div class="box-header with-border">
		<h3 class="box-title"><i class="fa fa-inr"></i> Fees Collection Details</h3>
   </div>
   <div class="box-body table-responsive no-padding">
   <?php
   	if(!empty($feesDetails)) {  
		echo '<table class="table">';
		echo '<col class="col-xs-1">';
		echo '<tr>';
		echo '<th class="text-center">SI No.</th>';
		echo '<th>Fees Details</th>';
		echo '<th>Description</th>';
		echo '<th>Amount</th>';
		echo '</tr>';
		foreach($feesDetails as $key=>$value) {
			echo '<tr>';
			echo '<td class="text-center">'.($key+1).'</td>';	
			echo '<td>'.$value['fees_details_name'].'</td>';
			echo '<td>'.$value['fees_details_description'].'</td>';
			echo '<td>'.$value['fees_details_amount'].'</td>';
			echo '</tr>';
			$totalAmount+=$value['fees_details_amount'];
		}
		echo '<tr><th colspan=3 class="text-right">Total Amount</th><th>'.$totalAmount.'</th></tr>';
		echo '</table>';
   	} else {
		echo '<div class="alert alert alert-danger" style="margin: 10px;">No Fees Data Available</div>';
	}
   ?>
   </div><!---./end box-body--->
</div><!---./end box--->

<!---Start display student list block---> 	
<div class="box-success box view-item col-xs-12 col-lg-12 no-padding">
   <div class="box-header with-border">
	<h3 class="box-title"><i class="fa fa-users"></i> Student Details</h3>
	<?php if(!empty($stuData)) : ?>
	<div class="box-tools pull-right"><?= Html::a('<i class="fa fa-file-pdf-o"></i> Generate PDF', ['export-fcc-wise-fees-pdf', 'fccid'=>$FccModel->fees_collect_category_id], ['class'=>'btn btn-sm btn-warning', 'target'=>'_blank', 'style'=>'color:#fff', 'data-method'=>'POST']) ?></div>
	<?php endif; ?>
   </div>
   <div class="box-body table-responsive no-padding">
   <?php
	if(!empty($stuData)) {
		echo '<table class="table table-striped">';
		echo '<tr>';
		echo '<th class="text-center">SI No.</th>';
		echo '<th>Student No</th>';
		echo '<th>Student Name</th>';
		echo '<th>Total Collection</th>';
		echo '<th>Paid Amount</th>';
		echo '<th>Unpaid Amount</th>';
		echo '<th>Action</th>';
		echo '</tr>';
		$sr = 1;
		foreach($stuData as $key=>$value) {
			$stuDetails = \app\modules\student\models\StuMaster::findOne($value);
			echo '<tr>';		
			echo '<td class="text-center">'.$sr++.'</td>';
			echo '<td>'.(!empty($stuDetails->stuMasterStuInfo->stu_unique_id) ? $stuDetails->stuMasterStuInfo->stu_unique_id : "(Not Set)").'</td>';
			echo '<td>'.$stuDetails->stuMasterStuInfo->name.'</td>';
			echo '<td>'.$totalAmount.'</td>';
			$payFees = $FptModel->getStuTotalPayFees($value, $FccModel->fees_collect_category_id);
			echo '<td>'.(!empty($payFees) ? $payFees : "0").'</td>';
			echo '<td>'.$actualCollect = ($totalAmount-$payFees).'</td>';
			echo '<td>'.Html::a('TakeFees', ['pay-fees', 'sid'=>$value, 'fcid'=>$FccModel->fees_collect_category_id], ["target"=>"_blank", 'class'=>'btn btn-block btn-primary']).'</td>';
			echo '</tr>';
			$gTotalAmount+=$totalAmount;
			$gpayFees+=$payFees;
			$gActualCollect+=$actualCollect;
		}
		echo '<tr class="bg-aqua"><th colspan=3 class="text-right">GRAND TOTAL </th>';
		echo '<th>'.$gTotalAmount.'</th>';
		echo '<th>'.$gpayFees.'</th>';
		echo '<th>'.$gActualCollect.'</th>';
		echo '<th></th></tr>';
		echo '</table>';	
	}
	else {
		echo '<div class="alert alert alert-danger" style="margin: 10px;">No student data available</div>';
	}
   ?>
   </div><!---./end box-body--->
</div><!---./end box--->

<?php endif; ?>

modules/fees/views/fees-payment-transaction/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\modules\fees\models\FeesPaymentTransaction */

$this->title = 'Fees Collection';
$this->params['breadcrumbs'][] = ['label'=>'Fees', 'url'=>['/fees']];
$this->params['breadcrumbs'][] = ['label' => 'Fees Collection', 'url' => ['collect']];
$this->params['breadcrumbs'][] = $FccModel->fees_collect_name;
$this->params['breadcrumbs'][] = $stuData->stuMasterStuInfo->name;
?>
<div class="col-xs-12">
  <div class="col-lg-4 col-sm-8 col-xs-12 no-padding"><h3 class="box-title"><i class="fa fa-plus"></i> <?= $this->title ?></h3></div>
</div>

<div class="fees-payment-transaction-create">
    <?= $this->render('_form', [
        'model' => $model,
	'stuData' => $stuData,
	'FccModel' => $FccModel,
    ]) ?>
</div>

modules/fees/views/fees-payment-transaction/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\fees\models\FeesPaymentTransactionSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Fees Payment Transactions';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="fees-payment-transaction-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Fees Payment Transaction', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'fees_pay_tran_id',
            'fees_pay_tran_collect_id',
            'fees_pay_tran_stu_id',
            'fees_pay_tran_batch_id',
            'fees_pay_tran_course_id',
            // 'fees_pay_tran_section_id',
            // 'fees_pay_tran_mode',
            // 'fees_pay_tran_cheque_no',
            // 'fees_pay_tran_bank_id',
            // 'fees_pay_tran_amount',
            // 'fees_pay_tran_date',
            // 'created_at',
            // 'created_by',
            // 'updated_at',
            // 'updated_by',
            // 'is_status',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>