modules/fees/controllers/DefaultController.php
<?php
/*****************************************************************************************
 * EduSec  Open Source Edition is a School / College management system developed by
 * RUDRA SOFTECH. Copyright (C) 2010-2015 RUDRA SOFTECH.

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses. 

 * You can contact RUDRA SOFTECH, 1st floor Geeta Ceramics, 
 * Opp. Thakkarnagar BRTS station, Ahmedbad - 382350, India or
 * at email address info@rudrasoftech.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * RUDRA SOFTECH" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by RUDRA SOFTECH".
 *****************************************************************************************/
/**
 * Default controllers it use as a dashboard for fees modules
 *
 * @package EduSec.modules.fees.controllers
 */

namespace app\modules\fees\controllers;

use yii\web\Controller;
use Yii;

class DefaultController extends Controller
{
    public function actionIndex()
    {
	$paidData = $unPaidData = $fcCategory = [];
	if(Yii::$app->session->get('stu_id'))
		return $this->redirect(['/fees/fees-payment-transaction/stu-fees-data']);
	
	//Course Wise Collection Count
	$cateWisePaid = 0;
	$courseWiseCollect = (new \yii\db\Query())
			->select(["(cs.course_name) AS '0'", 'SUM(fpt.fees_pay_tran_amount) AS "1"'])
			->from('fees_payment_transaction fpt')
			->join('JOIN', 'courses cs', 'cs.course_id = fpt.fees_pay_tran_course_id')
			->where(['cs.is_status'=>0, 'fpt.is_status'=>0])
			->groupBy('fpt.fees_pay_tran_course_id')
			->all();

	$actFcc = \app\modules\fees\models\FeesCollectCategory::find()->where(['is_status'=>0])->asArray()->all();
	
	foreach($actFcc as $v) {
		$stuCount = \app\modules\student\models\StuMaster::find()->where(['is_status'=>0, 'stu_master_batch_id'=>$v['fees_collect_batch_id']])->count();
		$fccTotal = \app\modules\fees\models\FeesCategoryDetails::getFeeCategoryTotal($v['fees_collect_category_id']);
		$cateWisePaid+=($stuCount*$fccTotal); 
	}

	$paidTotal = (new \yii\db\Query())->from('fees_payment_transaction fpt')
		     ->join('JOIN', 'fees_collect_category fcc', 'fpt.fees_pay_tran_collect_id = fees_collect_category_id')
		    ->where(['fcc.is_status'=>0, 'fpt.is_status'=>0])
		    ->sum('fpt.fees_pay_tran_amount');


	$paidPer =' ('.(($cateWisePaid!=0) ? round(($paidTotal*100)/$cateWisePaid, 2) : 0) . '%)';
	$unPaidPer =' ('.(($cateWisePaid!=0) ? round((($cateWisePaid-$paidTotal)*100)/$cateWisePaid, 2) : 0).'%)';

	$paidUnpaidData = [
				['name'=>'Paid'.$paidPer, 'y'=>$paidTotal, 'color'=>'#77C730'],
				['name'=>'Unpaid'.$unPaidPer, 'y'=>($cateWisePaid-$paidTotal), 'color'=>'#F45B5B'],
			];

	
	//Individual Fees Collection Category Wise
	$fcWiseDetails = (new \yii\db\Query())
		    ->select(['fees_collect_category_id', 'fees_collect_batch_id', "CONCAT(fcc.fees_collect_name,'(',bt.batch_name,')') AS fc_name"]) 
		    ->from('fees_collect_category fcc')
		    ->join('JOIN', 'batches bt', 'bt.batch_id = fcc.fees_collect_batch_id')
		    ->where(['fcc.is_status' => '0'])
		    ->orderBy('fcc.fees_collect_category_id DESC')
		    ->limit('10')
		    ->all();
	$fccTotal = $fccPaid = 0;
	foreach($fcWiseDetails as $k=>$v) {
		$stuCount = \app\modules\student\models\StuMaster::find()->where(['is_status'=>0, 'stu_master_batch_id'=>$v['fees_collect_batch_id']])->count();
		$fccTotalTmp = \app\modules\fees\models\FeesCategoryDetails::getFeeCategoryTotal($v['fees_collect_category_id']);
		$fccPaidTmp = (new \yii\db\Query())->from('fees_payment_transaction fpt')->where(['fpt.is_status'=>0, 'fpt.fees_pay_tran_collect_id'=>$v['fees_collect_category_id']])->sum('fpt.fees_pay_tran_amount');

		$fccTotal = $stuCount*$fccTotalTmp;
		$fccPaid = ($fccPaidTmp===NULL) ? 0 : $fccPaidTmp;
		$fccUnPaid = $fccTotal-$fccPaid;
		$fcCategory[] = $v['fc_name'];
		$paidData[] = $fccPaid;
		$unPaidData[] = $fccUnPaid;		
	}
	
	$fccWisePaidUnPaid = [
				['name'=>'Paid Amount', 'data'=>$paidData, 'color'=>'#77C730'],
				['name'=>'Unpaid Amount', 'data'=>$unPaidData, 'color'=>'#F45B5B'],
			];

	//Recently fees transaction
	$feeRecent = (new \yii\db\Query())
		    ->select(['fpt.fees_pay_tran_id', 'fpt.fees_pay_tran_amount', 'stu_unique_id', "CONCAT(si.stu_first_name, ' ', si.stu_last_name) AS 'stu_name'", 'fcc.fees_collect_name', 'DATE_FORMAT(fpt.fees_pay_tran_date, "%d-%m-%Y") AS tranDate']) 
		    ->from('fees_payment_transaction fpt')
		    ->join('JOIN', 'fees_collect_category fcc', 'fcc.fees_collect_category_id = fpt.fees_pay_tran_collect_id')
		    ->join('JOIN', 'stu_info si', 'si.stu_info_stu_master_id = fpt.fees_pay_tran_stu_id')
		    ->where(['fpt.is_status' => '0'])
		    ->orderBy('fees_pay_tran_id DESC')
		    ->limit(10)
		    ->all();


        return $this->render('index', ['feeRecent'=>$feeRecent, 
					'courseWiseCollect'=>$courseWiseCollect,
					'paidUnpaidData'=>$paidUnpaidData,
					'fccWisePaidUnPaid'=>$fccWisePaidUnPaid,
					'fcCategory'=>$fcCategory
				      ]
			    );
    }
}

modules/fees/controllers/FeesCollectCategoryController.php
<?php
/*****************************************************************************************
 * EduSec  Open Source Edition is a School / College management system developed by
 * RUDRA SOFTECH. Copyright (C) 2010-2015 RUDRA SOFTECH.

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses. 

 * You can contact RUDRA SOFTECH, 1st floor Geeta Ceramics, 
 * Opp. Thakkarnagar BRTS station, Ahmedbad - 382350, India or
 * at email address info@rudrasoftech.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * RUDRA SOFTECH" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by RUDRA SOFTECH".
 *****************************************************************************************/
/**
 * FeesCollectCategoryController implements the CRUD actions for FeesCollectCategory model.
 *
 * @package EduSec.modules.fees.controllers
 */

namespace app\modules\fees\controllers;

use Yii;
use app\modules\fees\models\FeesCollectCategory;
use app\modules\fees\models\FeesCategoryDetails;
use app\modules\fees\models\FeesCollectCategorySearch;
use app\modules\course\models\Batches;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use pheme\grid\actions\ToggleAction;
use yii\helpers\Json;

class FeesCollectCategoryController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function actions() 
    {
	    return [
		'toggle' => [
		    'class' => ToggleAction::className(),
		    'modelClass' => 'app\modules\fees\models\FeesCollectCategory',
		    'attribute' => 'is_status',
		    //'type'=> 'toggle-status',
		    // Uncomment to enable flash messages
		    'setFlash' => true,
		],
	    ];
    }	
    /**
     * Lists all FeesCollectCategory models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new FeesCollectCategorySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single FeesCollectCategory model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new FeesCollectCategory model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new FeesCollectCategory();

        if ($model->load(Yii::$app->request->post()) && isset($_POST['FeesCollectCategory'])) {

		$model->attributes = $_POST['FeesCollectCategory'];
		for($i=0;$i<count($_REQUEST['FeesCollectCategory']['fees_collect_batch_id']);$i++) :
			$model->fees_collect_category_id = NULL;
			$model->isNewRecord = true;
			$model->fees_collect_batch_id = $_POST['FeesCollectCategory']['fees_collect_batch_id'][$i];
			$model->fees_collect_name = $_POST['FeesCollectCategory']['fees_collect_name'];
			$model->fees_collect_details = $_POST['FeesCollectCategory']['fees_collect_details'];
			$model->fees_collect_start_date = Yii::$app->dateformatter->getDateFormat($_POST['FeesCollectCategory']['fees_collect_start_date']);
			$model->fees_collect_end_date = Yii::$app->dateformatter->getDateFormat($_POST['FeesCollectCategory']['fees_collect_end_date']);
			$model->fees_collect_due_date = Yii::$app->dateformatter->getDateFormat($_POST['FeesCollectCategory']['fees_collect_due_date']);
			$model->created_by = Yii::$app->getid->getId(); 
			$model->created_at = new \yii\db\Expression('NOW()');

			if($model->save()) {
			      Yii::$app->session->setFlash('green-'.$i, '<i class="fa fa-info-circle"></i> <b>Fees Category:</b> '.$_POST['FeesCollectCategory']['fees_collect_name'].' for <b>Batch: </b>'.Batches::findOne($_POST['FeesCollectCategory']['fees_collect_batch_id'][$i])->batch_name.' is created successfully');
			} else {
			      Yii::$app->session->setFlash('red-'.$i, '<i class="fa fa-warning"></i> The combination of <b>Fees Category:</b> '.$_POST['FeesCollectCategory']['fees_collect_name'].' and <b>Batch: </b>'.Batches::findOne($_POST['FeesCollectCategory']['fees_collect_batch_id'][$i])->batch_name.' has already been taken.');
			}
				
		endfor;
	
			return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing FeesCollectCategory model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {

		$model->attributes = $_POST['FeesCollectCategory'];
		$model->fees_collect_start_date = Yii::$app->dateformatter->getDateFormat($_POST['FeesCollectCategory']['fees_collect_start_date']);
		$model->fees_collect_end_date = Yii::$app->dateformatter->getDateFormat($_POST['FeesCollectCategory']['fees_collect_end_date']);
		$model->fees_collect_due_date = Yii::$app->dateformatter->getDateFormat($_POST['FeesCollectCategory']['fees_collect_due_date']);
		$model->updated_by = Yii::$app->getid->getId(); 
		$model->updated_at = new \yii\db\Expression('NOW()');

		if($model->save())
			return $this->redirect(['view', 'id' => $model->fees_collect_category_id]);
		else
			return $this->render('update', ['model' => $model,]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing FeesCollectCategory model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = FeesCollectCategory::findOne($id);
	$model->is_status = 2;
	$model->updated_by = Yii::$app->getid->getId(); 
	$model->updated_at = new \yii\db\Expression('NOW()');
	$model->save();

        return $this->redirect(['index']);
    }

    /**
     * Finds the FeesCollectCategory model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return FeesCollectCategory the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = FeesCollectCategory::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

modules/fees/views/fees-collect-category/FeesCollectCategoryExportPdfExcel.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
?>
<div class="fees-collect-category-index">
<?php  
	$org = app\models\Organization::find()->asArray()->one();
	$model->sort = false; 
	$dispColumn  = false;
	if($type == 'Excel') {
		$dispColumn  = true;
		echo "<table><tr> <th colspan='11'><h3>".$org['org_name']."</h3> </th> </tr> </table>";
	}
?>
<?= GridView::widget([
	'dataProvider' => $model,
	'layout' => '{items}',
	'columns' => [
		['class' => 'yii\grid\SerialColumn'],
			'fees_collect_name',
			'fees_collect_details',
		[
			'attribute' => 'fees_collect_batch_id',
			'value' => 'feesCollectBatch.batch_name',
		],

		[
			'attribute' => 'fees_collect_start_date',
			'value' => function ($model) {
				return Yii::$app->formatter->asDate($model->fees_collect_start_date);
			},
		],

		[
			'attribute' => 'fees_collect_end_date',
			'value' => function ($model) {
				return Yii::$app->formatter->asDate($model->fees_collect_end_date);
			},
		],
		[
			'attribute' => 'fees_collect_due_date',
			'value' => function ($model) {
				return Yii::$app->formatter->asDate($model->fees_collect_due_date);
			},
		],
		[
			'label' => 'Created At',
			'attribute' => 'created_at',
			'value' => function ($data) {
				return Yii::$app->formatter->asDateTime($data->created_at);
			},
			'visible'=>$dispColumn,
		],
		[
			'label' => 'Created By',
			'attribute' => 'created_by',
			'value' => 'createdBy.user_login_id',
			'visible'=>$dispColumn,
		],
		[
			'label' => 'Updated At',
			'attribute' => 'updated_at',
			'value' => function ($data) {
				return (!empty($data->updated_at) ? Yii::$app->formatter->asDateTime($data->updated_at) : " (not set) ");
			},
			'visible'=>$dispColumn,
		],
		[
			'label' => 'Updated By',
			'attribute' => 'updated_by',
			'value' => 'updatedBy.user_login_id',
			'visible'=>$dispColumn,
		],
	],
]); 
?>

</div>

modules/fees/views/fees-collect-category/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\fees\models\FeesCollectCategorySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="fees-collect-category-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'fees_collect_category_id') ?>

    <?= $form->field($model, 'fees_collect_name') ?>

    <?= $form->field($model, 'fees_collect_batch_id') ?>

    <?= $form->field($model, 'fees_collect_details') ?>

    <?= $form->field($model, 'fees_collect_start_date') ?>

    <?php // echo $form->field($model, 'fees_collect_end_date') ?>

    <?php // echo $form->field($model, 'fees_collect_due_date') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <?php // echo $form->field($model, 'is_status') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/fees/views/fees-collect-category/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\modules\fees\models\FeesCollectCategory */

$this->title = 'Add Fees Category';
$this->params['breadcrumbs'][] = ['label' => 'Fees Categories', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="col-xs-12">
  <div class="col-lg-4 col-sm-4 col-xs-12 no-padding"><h3 class="box-title"><i class="fa fa-plus"></i> Add Fees Category</h3></div>
  <div class="col-xs-4"></div>
  <div class="col-lg-4 col-sm-4 col-xs-12 no-padding" style="padding-top: 20px !important;">
	<div class="col-xs-4"></div>
	<div class="col-xs-4"></div>
	<div class="col-xs-4 left-padding">
	<?= Html::a('Back', ['index'], ['class' => 'btn btn-block btn-back']) ?>
	</div>
   </div>
</div>

<div class="fees-collect-category-create">
    <?= $this->render('_form', ['model' => $model,]) ?>
</div>

modules/fees/views/fees-collect-category/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\fees\models\FeesCollectCategorySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Manage Fees Categories';
$this->params['breadcrumbs'][] = ['label' => 'Fees', 'url' => ['default/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<?php
if(Yii::$app->session->hasFlash('green-0') || Yii::$app->session->hasFlash('red-0')) :
?>
<div class="col-xs-12">
  <div class="alert alert-dismissible" style="background-color: #FFFFFF;border-color: #00c0ef;">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	<span aria-hidden="true">&times;</span></button>
	<?php
		foreach (Yii::$app->session->getAllFlashes() as $key => $message) {
		     echo '<p class="text-'.preg_split('/[\s,-]+/', $key)[0].'" style="padding-bottom:10px">'.$message.'</p>';
		}
	?>
  </div>
</div>
<?php
endif;
?>

<div class="col-xs-12">
  <div class="col-lg-4 col-sm-4 col-xs-12 no-padding"><h3 class="box-title"><i class="fa fa-th-list"></i> <?= $this->title ?></h3></div>
  <div class="col-xs-4"></div>
  <div class="col-lg-4 col-sm-4 col-xs-12 no-padding" style="padding-top: 20px !important;">
	<div class="col-xs-4 left-padding">
        <?= Html::a('ADD', ['create'], ['class' => 'btn btn-block btn-success']) ?>
	</div>
	<div class="col-xs-4 left-padding">
	<?= Html::a('PDF', ['/export-data/export-to-pdf', 'model'=>get_class($searchModel)], ['class' => 'btn btn-block btn-warning', 'target'=>'_blank']) ?>
	</div>
	<div class="col-xs-4 left-padding">
	<?= Html::a('EXCEL', ['/export-data/export-excel', 'model'=>get_class($searchModel)], ['class' => 'btn btn-block btn-primary', 'target'=>'_blank']) ?>
	</div>
  </div>
</div>

<div class="col-xs-12" style="padding-top: 10px;">
   <div class="box">
      <div class="box-body table-responsive">
   	<div class="fees-collect-category-index">
	<?php Pjax::begin([
	'enablePushState' => false,
	]); ?>
	    <?= GridView::widget([
		'dataProvider' => $dataProvider,
		'filterModel' => $searchModel,
		'summary'=>'',
		'columns' => [
		    ['class' => 'yii\grid\SerialColumn'],

		    'fees_collect_name',
		    'fees_collect_details',
		    [
			'attribute' => 'fees_collect_batch_id',
			'value' => 'feesCollectBatch.batch_name',
			'filter' => ArrayHelper::map(app\modules\course\models\Batches::find()->where(['is_status' => 0])->all(), 'batch_id', 'batch_name', 'batchCourse.course_name')
	 	    ],

		    [
			'attribute' => 'fees_collect_start_date',
			'value' => function ($model) {
					return Yii::$app->formatter->asDate($model->fees_collect_start_date);
				   },
			'filter' => \yii\jui\DatePicker::widget([
		            'model'=>$searchModel,
		            'attribute'=>'fees_collect_start_date',
		            'clientOptions' =>[
		                'dateFormat' => 'dd-mm-yyyy',
		                'changeMonth'=> true,
		                'changeYear'=> true,
				'defaultValue'=>null,
				'yearRange'=>'1900:'.(date('Y')+1),
				'defaultDate'=> null,],
			     'options'=>[
				'class' => 'form-control',
		                'value' => NULL,
		              ],
		        ]),
			'format' => 'html',	
		    ],

		    [
			'attribute' => 'fees_collect_end_date',
			'value' => function ($model) {
					return Yii::$app->formatter->asDate($model->fees_collect_end_date);
				   },
			'filter' => \yii\jui\DatePicker::widget([
		            'model'=>$searchModel,
		            'attribute'=>'fees_collect_end_date',
		            'clientOptions' =>[
		                'dateFormat' => 'dd-mm-yyyy',
		                'changeMonth'=> true,
		                'changeYear'=> true,
				'defaultValue'=>null,
				'yearRange'=>'1900:'.(date('Y')+1),
				'defaultDate'=> null,],
			     'options'=>[
				'class' => 'form-control',
		                'value' => NULL,
		              ],
		        ]),
			'format' => 'html',	
		    ],
		    [
			'attribute' => 'fees_collect_due_date',
			'value' => function ($model) {
					return Yii::$app->formatter->asDate($model->fees_collect_due_date);
				   },
			'filter' => \yii\jui\DatePicker::widget([
		            'model'=>$searchModel,
		            'attribute'=>'fees_collect_due_date',
		            'clientOptions' =>[
		                'dateFormat' => 'dd-mm-yyyy',
		                'changeMonth'=> true,
		                'changeYear'=> true,
				'defaultValue'=>null,
				'yearRange'=>'1900:'.(date('Y')+1),
				'defaultDate'=> null,],
			     'options'=>[
				'class' => 'form-control',
		                'value' => NULL,
		              ],
		        ]),
			'format' => 'html',	
		    ],
		 
		    [
			'header' => 'Add Fees Details',
			'class' => 'yii\grid\ActionColumn',
			'template' => '{add_sub_head}',
			'buttons'=>[
		                      'add_sub_head' => function ($url, $model) {
					$url = \Yii::$app->getUrlManager()->createUrl(["fees/fees-category-details/create", 'fcc_id'=>$model->fees_collect_category_id]);     
		                        return Html::a('<span class="glyphicon glyphicon-plus text-aqua"></span>', $url, [
		                                'title' => Yii::t('yii', 'Add Sub Head'),'class' => 'text-center', 'style' => 'font-size:20px'
		                        ]);                                
		    
		                      }
		                  ],
			'contentOptions' => ['style' => 'text-align:center'],	
		    ],
		   [
			'class' => '\pheme\grid\ToggleColumn',
			'attribute' => 'is_status',
			'enableAjax' => false,
			'filter' => ['0' => 'Active', '1' => 'Inactive'],
			'contentOptions' => ['class' => 'text-center'],
	        ],

		    ['class' => 'app\components\CustomActionColumn'],
		],
	    ]);

  Pjax::end(); ?>
   	</div>
      </div>
    </div>
</div>

modules/fees/views/fees-collect-category/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\fees\models\FeesCollectCategory */

$this->title = 'Update Fees Category: ' . ' ' . $model->fees_collect_name;
$this->params['breadcrumbs'][] = ['label' => 'Fees', 'url' => ['default/index']];
$this->params['breadcrumbs'][] = ['label' => 'Fees Categories', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->fees_collect_name, 'url' => ['view', 'id' => $model->fees_collect_category_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="col-xs-12">
  <div class="col-lg-4 col-sm-8 col-xs-12 no-padding"><h3 class="box-title"><i class="fa fa-plus"></i> Update Fees Category</h3></div>
  <div class="col-xs-4"></div>
  <div class="col-lg-4 col-sm-4 col-xs-12 no-padding" style="padding-top: 20px !important;">
	<div class="col-xs-4"></div>
	<div class="col-xs-4"></div>
	<div class="col-xs-4 left-padding">
	<?= Html::a('Back', ['index'], ['class' => 'btn btn-block btn-back']) ?>
	</div>
   </div>
</div>

<div class="fees-collect-category-update">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>